services:
  postgis:
    build: ./postgis
    container_name: postgis
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgis/init:/docker-entrypoint-initdb.d:ro
      - ./start_data:/data:ro
      - pg_data:/var/lib/postgresql/data
      - shared:/shared
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -tAc \"SELECT 1 FROM information_schema.tables WHERE table_name = 'crash_road_match'\" | grep -q 1 && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -tAc \"SELECT 1 FROM crash_road_match LIMIT 1\" | grep -q 1" ]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 30
    command: >
      bash -c "declare -p | grep -E 'POSTGRES_' > /container.env 
      && cron 
      && docker-entrypoint.sh postgres"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env
    ports:
      - 15080:80
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json

  node-server:
    build: ./node-server
    container_name: node-server
    env_file: .env
    ports:
      - "3000:3000"

  geoserver:
    image: docker.osgeo.org/geoserver:2.28.0
    container_name: geoserver
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - geoserver_ext:/opt/geoserver/ext_dir
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE: %{http_code}

        ' http://localhost:8080/geoserver/web/ || exit 1"
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 30s
    restart: unless-stopped

  geoserver-init:
    image: alpine:latest
    depends_on:
      geoserver:
        condition: service_healthy
    volumes:
      - ./geoserver/init_geoserver.sh:/init_geoserver.sh
      - ./geoserver/roads.sld:/roads.sld:ro
      - ./start_data/roads:/shapefile_source
    env_file:
      - .env
    command: >
      /bin/sh -c "apk add --no-cache curl zip &&  sh /init_geoserver.sh"

  graphhopper:
    build: ./graphhopper
    depends_on:
      postgis:
        condition: service_healthy
    container_name: graphhopper
    ports:
      - 8989:8989
    env_file: .env
    volumes:
      - ./start_data/data.osm.pbf:/graphhopper/data.osm.pbf
      - ./graphhopper/config.yml:/graphhopper/config.yml
      - ./graphhopper/restart_graphhopper.cron:/etc/cron.d/restart_graphhopper:ro

  restarter:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared:/shared
    command: |
      sh -c '
      [ -f /shared/road_anxiety.done ] && rm -f /shared/road_anxiety.done
      echo "[$(date)] started, waiting for road_anxiety cron"
      while true; do
        while [ ! -f /shared/road_anxiety.done ]; do
          sleep 10
        done

        echo "[$(date)] anxiety_zones_match calculated, restarting graphhopper container."
        docker restart graphhopper

        rm -f /shared/road_anxiety.done
        echo "[$(date)] graphhopper container restarted."
      done
      '
    restart: unless-stopped




volumes:
  pg_data:
  geoserver_data:
  geoserver_ext:
  shared:
